Lib/__init__.py

supressed error message to screen

---

.travis.yml
Makefile.in
RELEASE-NOTES
Src/cmor_axes.c
Test/ipcc_test_code.json
Test/test_python_CMIP6_CV_furtherinfourl.json
Test/test_python_CMIP6_CV_furtherinfourl.py
run_tests.py

* Add new test suites and fix travis.yml
* Add polar stereographic examples
* Merge Emma Hogan exception signal branch (python_errror_handling)
* Delete create_output_path from pywraper.
* Add json-c include in Makefile.
* Fix zfactor variable not being written bug.

Cmor 3.1.2

---

Src/cmor.c
Src/cmor_CV.c
Src/cmor_variables.c
Test/cmor_speed_and_compression_02.py
include/cmor.h
include/cmor_func_def.h

@dnadeau4 I made some more changes related to #171; I continued to push to my branch, but this pull request shows the changes you already merged. I hope this won't cause any problems for you!
I'm not sure the changes to `cmor_CV.c` are required. I believe all the CV checks are run before the variable is initialised; should I revert those changes?

Only close variables if no error was encountered

---

setup.py.in

Reverts PCMDI/cmor#194
That broke my installation,  Need more work, so reverting.

Revert "Added extra_link_args to Extension arguments"

---

setup.py.in

All good, I was in the wrong environment.

"Added extra_link_args to Extension arguments"

---

Src/cmor.c

Flush the buffer so messages are written to the log immediately

---

LibCV/PrePARE/PrePARE.py

This rollback different return code depending on PrePARE diagnostic:
-   0 = no errors
-   more than 0 = errors (with code = number of files with error(s)) 
-   -1 = all files has error(s)
Note: this doesn't work properly as `cmip6_cv.check_filename()` doesn't return 1 in case of wrong filename. See [https://github.com/PCMDI/cmor/issues/323](https://github.com/PCMDI/cmor/issues/323)

Add safe return code

---

.travis.yml
Src/cmor.c
Src/cmor_CV.c
scripts/conda_upload.sh

Issue 349 empy source

---

scripts/CMIP6_CV_cron_github.sh
scripts/README_Update_CV.md
scripts/createCMIP6CV.py

@mauzey1 once you're happy with this script we need to put it on some pcmdi web machine as a cronjob

new script for cron job

---

Makefile.in
Test/CMIP6_sample_CMOR_driver.f90
Test/CMOR_input_example.json

Adding Fortran sample code from issue #344

Adding Fortran sample code from issue #344.

---

Test/CMOR_input_example.json
Test/test_doc.py

After discussions with @durack1, I have put some comments into the examples which I think would help someone who has no experience with CMOR get started.

Update example files with comments

---

.circleci/config.yml
.travis.yml

Fix CircleCI and Travis configurations

---

.circleci/config.yml
.travis.yml
Src/cmor_tables.c
recipes/cmor/meta.yaml.in

Change error for missing tables from CMOR_WARNING to CMOR_CRITICAL

---

recipes/cmor/build.sh
scripts/conda_upload.sh
setup.py.in

Resolves #511
This also resolves part of #512 by using the latest version of conda-build instead of keeping it at version <3.3.

Fix nightly builds

---

LibCV/PrePARE/PrePARE.py

Check pressure level dimension size attribute for pressure levels test in PrePARE.

---

Test/test_cmor_grid_unstructured_3d_fabi.c

Modified test_cmor_grid_unstructured_3d_fabi.c

---

Src/cmor_variables.c

Resolves #450 
Apply change suggested in https://github.com/PCMDI/cmor/issues/450#issuecomment-473365915

Change missing value history message

---

Src/cmor_tables.c

Return error when tables are not found.

---

README.md

@dnadeau4 The CircleCI tests are failing due to a conda server error but this change should not effect the build.  Merging it could get the nightly builds working since they also got hit with a conda server error.

Update Zenodo DOI

---

recipes/conda-envs/cmor-3.5.0.yaml

Completes an item on #478 
> Update conda env export > cmor_3.5.0.yaml file

Add conda env file for CMOR 3.5.0

---

.circleci/config.yml

Create separate step in CircleCI tests for testing CMOR with CDMS2

---

.circleci/config.yml
.travis.yml
recipes/cmor/meta.yaml.in

Update the build to use libnetcdf 4.7.3 for the latest version of cdms2.

Pin libnetcdf 4.7.3 and openblas 0.3.6

---

Test/test_python_free_wrapping_issue.py
Test/test_site_ts.py

Update test_site_ts.py to remove error

---

LibCV/PrePARE/PrePARE.py
Src/cmor_CV.c
Test/test_python_CMIP6_CV_parenttimeunits.py

Fix count of files with errors in PrePARE

---

configure
configure.ac

Test for the function 'json_object_new_object' when testing json-c in the configure script.

---

.circleci/config.yml

Pin clang_osx-64 9.0.1

---

recipes/conda-envs/cmor-3.6.0.yaml

Add CMOR 3.6.0 environment file

---

Test/test_python_sos_psu_units.py

Don't delete the CMIP6 directory while testing

---

.circleci/config.yml

Add Python 3.10 build

---

Src/cmor.c

Fix message typo

---

.circleci/config.yml

Update CircleCI Linux image to ubuntu-2004:202201-02

---

README.md

add PCMDI logo #692

---

.circleci/config.yml

Python 3.12 build

---

README.md

Fix #734 
@mauzey1 please review and merge if all is ok

update README.md to remove CMOR3.7 ref

---

.circleci/config.yml

Update CircleCI Ubuntu image to 2024.01.2

---

Src/_cmormodule.c
setup.py.in

NumPy 2.0 support

---

Src/cmor_variables.c

fix typos (#772)

---

README.md

An update to the platform, version, and download stats for the conda-forge builds.  Stats are now up-to-date with latest release.

Update conda badges README.md

---

Src/cmor_tables.c

Resolves #803 
The new validation will now catch the error in the CV JSON posted in #803.  It will now throw an error instead of experiencing a segfault.
Below is the output from the example code.
```
Processing: files_for_obs4mips_v10/199508-C3S-L3_OZONE-O3_PRODUCTS-MERGED_UV-MERGED-ALG-MONTHLY-v0100.nc
Processing: files_for_obs4mips_v10/199507-C3S-L3_OZONE-O3_PRODUCTS-MERGED_UV-MERGED-ALG-MONTHLY-v0100.nc
Processing: files_for_obs4mips_v10/199509-C3S-L3_OZONE-O3_PRODUCTS-MERGED_UV-MERGED-ALG-MONTHLY-v0100.nc
C Traceback:
! In function: cmor_load_table_internal
! 
!
! Error: Your JSON file is invalid! Please use https://jsonlint.com/ to validate your file.
!
! Syntax Error in table: Tables/obs4MIPs_CV.json
!
C Traceback:
! In function: …
```

More robust JSON validation when loading tables

---

NOTICE
README.md

Add open source release identifier to README and add NOTICE file

---

Lib/pywrapper.py

Clean up doc strings in pywrapper.py
