- INSTALL
This change removes mention of the `--with-hdf5` option to configure
(which was not supported), and notes that NetCDF's `nc-config` is used
to find suitable options, and can be used to check what library and
include directories will be used.
It also slightly tidies (wraps some lines) in `INSTALL`
There is no change to anything other than documentation.
> Clarify instructions for HDF5 in INSTALL.

- Src/cmor.c
- include/cmor.h
As agreed in the final version of the PID services white paper, the tracking_prefix will now only be written if the project_id is set to (exactly) "CMIP6" to prevent accidental use of the prefix in other projects.
Successfully tested by Jörg against CORDEX data with modified cmor tables.
> tracking_prefix now filtered so it only applies if CMIP6 project_id is set

- Lib/pywrapper.py
#67 was closed, but `create_output_path` still exists in `pywrapper.py`; this pull request removes `create_output_path` from `pywrapper.py`.
> Remove create_output_path from pywrapper.py

- Lib/__init__.py
- Lib/pywrapper.py
- Src/_cmormodule.c
- Src/cmor.c
Contrary to [my previous comment](https://github.com/PCMDI/cmor/issues/65#issuecomment-227139826), it is not possible to catch exceptions using the current version of CMOR. To test whether I could catch an exception when attempting to produce an output netCDF file for a variable and then go on to produce an output netCDF file for a second (different) variable, I added the following lines to the [CMIP6 example](https://github.com/PCMDI/cmor/blob/master/Test/test_python_CMIP6_experimentID.py) after the `cmor.load_table` call:
```
try:
print 'In try loop'
ivar = cmor.variable(table_entry='soga', axis_ids=[], units='0.001')
except BaseException as err:
print 'In except loop'
print err
finally:
print 'In finally loop'
print 'Continuing'
```
When I run the edited example I get:
```
% …
```
> Python error handling

- Src/cmor.c
While testing CMOR 3.2.3, I discovered an issue related to accessing the variable-specific realm values from the MIP tables. This pull request fixes the issue.
Some details: `var_id` is used as an index for `cmor_vars`. However, it is not appropriate to use this index to access the appropriate variable from the MIP table (i.e. in `cmor_tables[nVarRefTblID].vars[var_id]`). 
In CMOR 3.2.2, `nVarRefTblID` was used in place of `var_id` as the index (see [here](https://github.com/PCMDI/cmor/blob/3.2.2/Src/cmor.c#L2624)). For the `Omon` and `SImon` tests I have, `nVarRefTblID` has a value of 0, meaning the realm value of the first variable in the MIP table was used. Coincidentally, the realm value of the first variable in the `Omon` and `SImon` MIP tables is the same as the realm value of the …
> Correct access to the variable-specific realm value

- Src/cmor.c
- include/cmor.h
Prior to the inclusion of #86, if an error was encountered, CMOR would exit immediately, meaning there would be no opportunity to call `cmor_close`; this meant the name of the output netCDF file would remain with the temporary string, rather than be finalised to include the start and end dates. Now, with the inclusion of #86, errors can be caught, meaning that `cmor_close` can be called on variables where an error was encountered. This can lead to misleading results; when I see an output netCDF file with a name that contains the start and end dates, I assume the file was generated correctly. However, this assumption no longer holds.
This pull request contains an idea of how to revert the behaviour of CMOR prior to the inclusion of #86.
Some details:
* An `error` attribute was added to the …
> Only close variables if no error was encountered

- Makefile.in
There are no Python files for two of the Python tests. I have commented these out so that `make test_python` succeeds. Alternatively, these files could be added in again.
> Commented out old tests

- setup.py.in
extra_link_args -Wl,-rpath,/path/to/shared/libs may be passed by configure, but not used to build the python extension. As a result, the resulting .so binaries have no rpath to find shared libraries, and environmental LD_LIBRARY_PATH must be defined to locate them. This fix avoid the need to set LD_LIBRARY_PATH.
> Added extra_link_args to Extension arguments

- Src/cmor.c
> Add to ierr rather than overwrite

- .gitignore
- include/cmor_locale.h
Removed inlcude/cmor_locale.h, which has been added to .gitignore.
> 392 ignore cmor_locale.h

- Test/test_cmor_grid_unstructured_fabi.c
The long_coords and lat_coords arrays were being accessed out-of-bounds, and lon_vertices and lat_vertices didn't look like they were being accessed correctly.
> Fixed test_cmor_grid_unstructured_fabi.c

- .travis.yml
- scripts/conda_upload.sh
When running the Travis builds, the home directory of the Docker containers isn't the same as the cmor directory.  This makes conda_uploads.sh not go to the recipes directory, which would be in /travis_home/recipes in the container.  This PR adds the variable CMOR_RECIPE_DIR for conda_upload.sh to find the recipe directory.
> Use CMOR_RECIPE_DIR to point conda_upload.sh to the recipe directory

- Lib/pywrapper.py
- Makefile.in
- Test/test_cmor_python_not_enough_data.py
- Test/test_python_CMIP6_CV_not_enough_data.py
Resolves #485
This change checks the amount of data being passed to cmor.write in Python if it is the expected amount for the amount of time passed (either by setting ntimes_passed or passing time values).  It will throw an exception if the amount is lower than expected (or if ntimes_passed is negative).
I also added a test to see if the exception is being thrown.
As for Fortran, it looks like it already handles this issue.
https://github.com/PCMDI/cmor/blob/8a48023d6456b596df5f0a1a9440bc3fe4d2634c/Src/cmor_fortran_interface.f90#L1032-L1037
> Throw exception if not enough data is passed to cmor.write in Python

- .circleci/config.yml
- .travis.yml
- Src/cmor.c
- Src/cmor_CV.c
Resolves #508 
@wachsylon pointed out that the latest version of json-c no longer uses `TRUE` and `FALSE` macros and just use the values 1 and 0, which were what the macros represented.
> Replace json-c macros TRUE and FALSE with 1 and 0

- scripts/conda_upload.sh
@doutriaux1 
The current Travis builds are working for Python 3.6 and 3.7 but not for 2.7.  The Python 2.7 build in Travis has a bunch of these errors when installing  conda-build
```
CondaMultiError: InvalidArchiveError(u'Error with archive /root/miniconda/pkgs/traitlets-4.3.2-py27_0.conda.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nChild process exited with status 127 (errno=-1, retcode=-30, archive_p=94748270522976)',)
InvalidArchiveError(u'Error with archive /root/miniconda/pkgs/decorator-4.4.0-py27_1.conda.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nChild process exited with status 127 (errno=-1, retcode=-30, archive_p=94748273217232)',)
InvalidArchiveError(u'Error …
```
> Use the latest version of Miniconda 2 in Travis

- Src/cmor.c
> Append pid number to temporary files used for testing output directory permissions

- Src/cmor_grids.c
If the grid mapping variable has the attribute `false_northing` then a
variable with standard name `projection_y_coordinate` has to exist. If
attribute `false_easting` is set, a variable with standard name
`projection_x_coordinate` has to exist. In the error message for
"`false_northing` is set but `projection_x_coordinate` does not exist"
contained two copy-&-paste errors. They are fixed now.
> fixed user output in cmor_grids: false_northing

- .circleci/config.yml
- .travis.yml
- recipes/cmor/build.sh
- recipes/cmor/meta.yaml.in
- setup.py.in
Fixes #555 
Upgrade Xcode from 9.2.0 to 11.1.0.
Additionally, use libnetcdf 4.6.2 to maintain compatibility with cdms2.
> Upgrade CircleCI MacOS tests to Xcode 11.1.0

- .circleci/config.yml
- .travis.yml
- recipes/cmor/meta.yaml.in
Pin libnetcdf and openblas in the CMOR recipe to make it compatible with the cdms2 in conda-forge.  Use openblas 0.3.6 in the testing environment.
> Pin libnetcdf and openblas for cdms2 compatibility

- .circleci/config.yml
- .travis.yml
- recipes/cmor/meta.yaml.in
Closes #564 
The OSX builds in CircleCI have been downloading numpy 1.11, which is outdated and causing errors in the build.  The PR will pin numpy version 1.14.6 and greater.
This PR will also pin libnetcdf 4.6.2 so that we can use the nightly CDMS2 builds again.
> Pin libnetcdf 4.6.2 and numpy >= 1.14.6

- LibCV/PrePARE/PrePARE.py
> Check if "external_variables" exists when values are present in "cell_measures".

- Src/cmor_CV.c
- Test/CMOR_input_example.json
- Test/common_user_inputNOBOUNDS.json
- Test/common_user_input_NOID.json
- Test/common_user_input_hier.json
- Test/test_python_CMIP6_CV_badsourcetypeCHEMAER.json
- Test/test_python_CMIP6_CV_forcenoparent.py
Fixes #553 
This PR will make the function cmor_CV_checkExperiment throw an error if the activity_id is inconsistent with the experiment_id in CMIP6_CV.json.  This change has the same effect on parent_activity_id and parent_experiment_id attributes in the user input JSON, which required changing some of the user input examples for tests.
> Make PrePARE give an error if the activity_id is wrong.

- LibCV/PrePARE/PrePARE.py
Resolves #532 
PrePARE will output its version of CMOR using `--version` or `-v`
```
$ PrePARE -v
PrePARE 3.5.0
```
> Add version argument to PrePARE

- Test/CMOR_input_TestTables.json
- Test/CMOR_input_example.json
- Test/baddirectory.json
- Test/cmor_speed_and_compression.json
- Test/common_user_inputNOBOUNDS.json
- Test/common_user_input_NOID.json
- Test/common_user_input_hier.json
- Test/metadata-template.json
- Test/test_python_CMIP6_CV_badsourcetypeCHEMAER.json
- include/cmor.h
Resolves #488 
This change is meant to maintain consistency with the https://github.com/WCRP-CMIP/CMIP6_CVs documentation mentioned in https://github.com/PCMDI/cmor3_documentation/issues/55.
> Change "_control_vocabulary_file" to "_controlled_vocabulary_file" in user input file.

- Lib/pywrapper.py
- Test/test_python_cfmip_site_axis_test.py
- Test/test_python_free_wrapping_issue.py
- Test/test_python_history.py
- Test/test_python_missing_values.py
- Test/test_python_user_interface_00.py
> Improve error messages for supported data types in pywrapper

- LibCV/PrePARE/PrePARE.py
Resolves #534 
@alaniwi @sashakames
These changes add two new features to PrePARE.
* Hide the number of files completed progress counter using the argument `--hide-progress`
* Remove terminal text color codes from the output using the argument `--no-text-color`
This PR also includes a change that allows the output of PrePARE when running with `--max-processes 1` to output to a log file when using `--log`.
> Add ability to remove text colors and hide file progress in PrePARE

- LibCV/PrePARE/PrePARE.py
@alaniwi
PrePARE will output the file's name for most errors.  However, there were three kinds of errors where PrePARE did not output a name.
These errors are when:
* The variable is not found in the table.
* The variable in the file name is not in the file.
* The variable does not have an entry in the table.
This was why the file name was not displayed for the error in https://github.com/PCMDI/cmor/issues/534#issue-479264683.  This PR will make PrePARE output the file names for files with these errors.  This may also satisfy #533 since PrePARE already reports file names for other errors.
> Output file names for errors in PrePARE

- LibCV/PrePARE/PrePARE.py
Fixes #587 
Before checking the value for `cell_methods`, remove the sections inside of parentheses and remove excess white space.
> Improve checking of cell_methods values in PrePARE

- .circleci/config.yml
The miniconda setup script from the CDAT repo was not working for the OSX builds in CircleCI.  This was due to the `curl` command needing the `-L` option for following redirects.  I have replaced the cloning of the CDAT repo with lines in config.yml that download and run the miniconda bash script.
> Fix miniconda setup

- .circleci/config.yml
The OSX builds have been failing due to older versions of the clang compiler being installed in the environment setup.  This change will pin the latest versions of the compilers in the CircleCI configuration file.
> Pin compiler versions

- .circleci/config.yml
- .gitignore
- .travis.yml
- Lib/pywrapper.py
- Src/_cmormodule.c
- Src/_controlvocabulary.c
- Test/test_python_user_interface_00.py
Adding support for Python 3.8 to CMOR.
Some changes needed to be made in _cmormodule.c for changes in 3.8.  `PyCMOR_zfactor` was having issues with list of axis ids that had a length of one as it was trying to read them as scalars using `PyLong_AsLong`.  This was causing an error in this section of a test.
https://github.com/PCMDI/cmor/blob/2b8af958b0615c975005dfec361edd3f3ce67c35/Test/test_python_user_interface_00.py#L116-L120
To fix this, I replaced checking if the number of axis ids was greater than 1 with checking if the axis id object was a scalar using `PyArray_CheckAnyScalar`.
https://github.com/PCMDI/cmor/blob/53d53fc51246556b3a406c12bfd2091792fc9078/Src/_cmormodule.c#L674-L686
There was a similar section in `PyCMOR_write` with the number of times passed.  This was not causing …
> Python 3.8 support

- .circleci/config.yml
- .gitignore
- .travis.yml
- recipes/cmor/meta.yaml.in
This will unpin libnetcdf 4.7.3 from the nightly build to allow libnetcdf 4.7.4 to be used by the Python 3.6, 3.7, and 3.8 builds, while the Python 2.7 builds will still use libnetcdf 4.7.3.
> libnetcdf update

- Test/test_sdepth1_float.c
The test_sdepth1_float test has an error where the time axis is not being properly initialized due to the index not being multiplied by 2.
> Fix time axis for test_sdepth1_float

- .circleci/config.yml
- recipes/cmor/conda_build_config.yaml
A recent change to the OSX Fortran compiler is causing issues similar to the one in #614.  This will apply the same pinning of gfortran to OSX builds.
> Pin gfortran 7.5.0 for OSX

- .circleci/config.yml
- .travis.yml
- recipes/cmor/conda_build_config.yaml
closes #619 
I have updated the CircleCI config to be similar to that used by [CDAT/vcsaddons](https://github.com/CDAT/vcsaddons/blob/1b0b31fd5f8774b9bef6b42e90d1e97fc334dc67/.circleci/config.yml).  It uses the build tools from [CDAT/conda-recipes](https://github.com/CDAT/conda-recipes/tree/fbd8a0560ffa0cc1f541d33201aa879413565f81/build_tools) to build conda packages.
This PR also adds Python 3.9 support to CMOR.
> Updated CircleCI config and Python 3.9 support

- LibCV/PrePARE/PrePARE.py
Apologies for doing a PR with a fork.
As described by @martinjuckes in #624, the fix involves checking the type string of a global attribute, not the value of the attribute itself.
I've tested the fix with `tas_day_EC-Earth3_historical_r1i1p1f1_gr_18500101-18501231.nc`, with the following result
```
=====================================================================================
branch_time_in_child is not a double: <class 'str'>
=====================================================================================
=====================================================================================
branch_time_in_parent is not a double: <class 'str'>
=====================================================================================
└──> :: CV FAIL    :: …
```
> fixed type checking in PrePARE

- Src/cmor_CV.c
- Test/test_python_CMIP6_CV_badgridresolution.py
Resolves #638 
This replaces the lengthy error message containing a regular expression string with a smaller message that only lists the section of the CV where the valid values for the attribute are located.  This is to help prevent the message from going over the maximum string length.
Previous message:
```
C Traceback:
! In function: _CV_ValidateAttribute
! called from: _CV_checkGblAttributes
! 
!
! Error: The attribute "nominal_resolution" could not be validated. 
! The current input value is "335 km" which is not valid 
! Valid values must match the regular expression:
!       ["^0.5 km$" "^1 km$" "^10 km$" "^100 km$" "^1000 km$" "^10000 km$" "^1x1 degree$" "^2.5 km$" "^25 km$" "^250 km$" "^2500 km$" "^5 km$" "^50 km$" "^500 km$" "^5000 km$" ] 
! 
! Check …
```
> Reduce length of error message when value cannot be validated

- Src/_cmormodule.c
- include/cmor_func_def.h
I removed two leftovers from the earlier part of the development, when one would need to perform an explicit call to the function creating the leadtime coordinate. Because it's all internalised now, there is no need for exposing that part of the CMOR code, and provide Python (or Fortran) API.
> remove unused part of the interface

- LibCV/PrePARE/PrePARE.py
- Src/cmor_CV.c
> Check if experiment_id attribute is present in current dataset when being processed by PrePARE

- LibCV/PrePARE/PrePARE.py
Fixes #654 
The regex will now only remove multiple comment sections rather everything between them.
```
"longitude: sum (comment: basin sum [along zig-zag grid path]) depth: sum time: mean (interval: 1 month)"
```
becomes...
```
"longitude: sum  depth: sum time: mean "
```
instead of...
```
"longitude: sum "
```
> Properly remove multiple comment sections from cell_methods values

- LibCV/pywrapper.py
- Src/_controlvocabulary.c
Fixes #670 
I discovered that PrePARE was failing at the check_filename function of Python 3.10 builds.  It was due to an error occurring with a PyArg_ParseTuple call.
https://github.com/PCMDI/cmor/blob/7cb3f2a0ea22defe24019626c5260e6514678c21/Src/_controlvocabulary.c#L13-L37
The PyArg_ParseTuple call was using the argument format `iis#s#s#`, where the `s#` was meant to both get the value of a string and its length.  This was not working correctly in Python 3.10 as the string and length variables were not being initialized with the argument values.
It turned out that using the argument format of `iisss` didn't have this issue.  This means that we get the string values without their lengths.  However, the lengths of the strings were not necessary for the file checking function so the …
> Fix PrePARE for Python 3.10 builds

- Src/cmor.c
- Test/test_python_forecast_coordinates.py
- TestTables/CMIP6_Amon.json
This is is a fix to a bug that causes CMOR failure when doing multiple writes to the dataset with seasonal forecast time coordinates ('reftime' and 'leadtime'). The original implementation didn't take into account a fact that a coordinate definition could happen only once and the code would fail during a second write() call.
> Multiple write bug

- .circleci/config.yml
- Lib/pywrapper.py
- Test/test_python_2Gb_file.py
- Test/test_python_2Gb_slice.py
- Test/test_python_open_close_cmor_multiple.py
Resolves #687 
Due to the removal of deprecated aliases in the latest version of NumPy ([1.24](https://numpy.org/doc/stable/release/1.24.0-notes.html#expired-deprecations)), the aliases `numpy.int` and `numpy.float` have been replaced with `int` and `float` respectively in the Python API.
This PR also resolves an issue with CDMS2 still using the deprecated aliases by using the older NumPy 1.23 when testing with CDMS2.
> Remove deprecated NumPy aliases for int and float

- .circleci/config.yml
- Makefile.in
This is to help simplify the testing process for source builds.  `make test` will now also run the CMIP6 CV Python tests that were once ran using testsrunner.
> Merge CMIP6 CV tests into Makefile test section

- .circleci/config.yml
- Src/cmor_variables.c
- configure
- configure.ac
Resolves #706 
This PR will replace the use of `int` with `size_t` in the function `cmor_write_var_to_file` when calculating the number of elements in an array.  This will allow `cmor_write` to write data arrays with more than 2^31-1 elements.
> 706 writing large volume of data

- Lib/__init__.py
- Lib/pywrapper.py
- Src/cmor.c
Fixes for #710 and removal of a leftover Python function (as there is no need to insert the leadtime coordinate manually).
> issue 710: fixing implicit declarations and updating Python API

- .circleci/config.yml
The rerendering step for the nightly builds have been really slow.  They have been taking up to 30 minutes to complete.  The issue was caused by trying to install the conda build packages into the base miniconda environment.  Installing to the base environment made conda process package conflicts, which can take a long time and will sometimes cause the build to fail if it takes too long.
The solution was to have the rerender step create another conda environment with the conda build packages.  This has reduced the time of the rerender step from around 30 minutes to around 1 minute.
> Speed up rerender for nightly builds

- Src/cmor.c
- Src/cmor_CV.c
- Test/CMIP6Plus_user_input.json
- Test/CMOR_input_example_badfurtherinfourl.json
- Test/test_cmor_CMIP6Plus.py
- Test/test_python_CMIP6_CV_badfurtherinfourl.py
This PR will make CMOR only add a `further_info_url` attribute to the file if it is either required by the CV, or set in the user input file.  If `further_info_url` is in the `required_global_attributes` section of the CV, it will require CMOR to add that attribute to the file.
The `further_info_url` attribute value provided by the user in the input file is a template that will be used by CMOR to generate a URL.  If the user doesn't provide a template value when it is required, then CMOR will use its built-in default template for the URL.  If the CV file provides a value for `further_info_url` in the `source_id` entry, then it will be used as a value for the file's attribute unless `further_info_url` is set in the user input.
> Make further_info_url attribute only be used if required by CV or requested by user

- .circleci/config.yml
- rebuild_meta_yaml.py
Replace the use of [CDAT/conda-recipes](https://github.com/CDAT/conda-recipes/tree/master/build_tools) for nightly builds of CMOR with tools in this repo.  The [cmor-feedstock repo](https://github.com/conda-forge/cmor-feedstock) is cloned, a script edits the meta.yaml of the feedstock, and then conda-smithy is used to rerender the feedstock and build the conda packages.
> Remove the use of the conda-recipe repo in the CI pipeline

- Src/cmor_tables.c
Closes #736 
This will remove the setting of the `realm` attribute to the default value of `REALM`.  `realm` will still be set to the `modeling_realm` attribute's value from the variable's table even if `realm` is not a required attribute in the CV.
> Remove default value for attribute 'realm'

- .circleci/config.yml
- .github/workflows/nightly-build.yml
Replaces miniconda in our development pipeline with miniforge.  A workaround until we can come up with a pip-installed alternative for CMOR.
Motivated by discussion in #768.
> Migrating CI to miniforge and mamba

- Src/cmor.c
- Src/cmor_CV.c
- Src/cmor_variables.c
- Test/test_cmor_zstandard_and_quantize.py
- include/cmor.h
Resolves #765
CMOR will now only apply quantization to the dataset variable and not the axes, zfactors, or grids. When quantization is applied, the variable `quantization_info` will be created in the netCDF file that will contain the quantization algorithm used (`bitgroom`, `bitround`, and `granular_bitround`) and the libnetcdf library version. The dataset variable will now have the attribute `quantization_nsb` or `quantization_nsd` depending on the algorithm used.
@durack1 @taylor13 @czender
> Make quantization meet CF compliance

- Makefile.in
- Src/cmor.c
- Src/cmor_CV.c
- Src/cmor_tables.c
- Src/cmor_variables.c
- Test/test_python_branded_variable.py
- TestTables/CMIP6_Omon_branded_variable.json
- include/cmor.h
These changes will allow CMOR to process variables that have a "branding suffix" in their table entry name as defined in #762.
There are also minor fixes to error messages for when`grid_label` or `nominal_resolution` are missing from the CV file.
> Handle variables that have a branding suffix

- configure
- configure.ac
The `CFLAGS` and `LDFLAGS` variables were used opposite of their intended usage for the `udunits2` and `netcdf` external dependencies, so correct them.
* `configure`: regenerate from...
* `configure.ac`: use correct `CFLAGS` and `LDFLAGS` variables
> configure: use correct CFLAGS and LDFLAGS variables

- .circleci/config.yml
- .github/workflows/nightly-build.yml
Resolves #782 
Build nightly from the repo directory of the CI process instead of cloning it with a URL.  This should allow pull requests from forks to be built and tested in the CI pipeline if permitted.
> Allow CI to run pull requests from forks

- .circleci/config.yml
- .github/workflows/nightly-build.yml
This PR replaces the calling of the soon-to-be deprecated mamba.sh script with `eval "$(mamba shell hook --shell bash)"`.
It also removes the call to `mamba search`, which was causing an error with the message `specs is required`. Rather than trying to debug this issue I removed the command since it was just displaying package information for CMOR that was already being provided by the `mamba create` command.
> Updates to CI

- Lib/__init__.py
- Lib/pywrapper.py
- Makefile.in
- Src/_cmormodule.c
- Src/cmor.c
- Src/cmor_cfortran_interface.c
- Src/cmor_fortran_interface.f90
- Src/cmor_grids.c
- Test/test_cmor_crs.py
- Test/test_python_CMIP6_projections.py
- include/cmor.h
- include/cmor_func_def.h
Resolves #774 
This PR adds the function `cmor_set_crs` to CMOR.  This function is similar to `cmor_set_grid_mapping` as it takes a grid mapping name along with other attributes to create a dimensionless variable for that grid mapping.  The difference is that the variable will be named `crs` instead of the grid mapping name, and will have the option for a text attribute named `crs_wkt`.  The `crs_wkt` attribute is added by CMOR but is not validated as a Well-known Text (WKT) string.
> Add function for creating a CRS variable in files

- .circleci/config.yml
- .github/workflows/nightly-build.yml
- autoconf-workaround.patch
Applies a workaround to a bug found in conda-forge's autoconf (see https://github.com/conda-forge/autoconf-feedstock/issues/41).
The path to `m4` needs to be set within the conda environment used by `conda-build` before running `autoconf`.
```
export M4=$(which m4)
autoconf
```
> Autoconf bug workaround

- Makefile.in
- Src/cmor_variables.c
- Test/test_cmor_nan_check.py
- Test/test_python_cfmip_site_axis_test.py
Resolves #802 
If variable data or zfactor data contains NaN values, then `cmor_write` will throw an error with the following message.
```
C Traceback:
! In function: cmor_write_var_to_file
! called from: cmor_create_var_attributes
! 
!
! Error: Invalid value(s) detected for variable 'orog' (table: CFsubhr): 1 values were NaNs. 
! First encountered NaN was at (axis: index/value): site: 2/3
!
! MIP data (missing values or otherwise) must not include "NaN's". Please replace all "NaN's" with an acceptable actual number.
! If you consider the "NaN's" to be missing, then replace them with the official "missing_value", which for CMIP floating point numbers is 1.e20.
!
```
> Reject data containing NaNs

- Makefile.in
- Src/cmor_axes.c
- Test/test_cmor_unsupported_calendar.py
- compile_line.txt.in
Resolves #813 
If a CF calendar name that is unsupported by CMOR is used for the attribute `calendar`, then CMOR will throw an error.
```
C Traceback:
! In function: cmor_calendar_c2i
! called from: cmor_close_variable
! 
!
! Error: A utc calendar is not currently an option for MIP results.
! Please adopt a different, more common calendar used for climate studies
!
```
> Catch unsupported CF calendars as errors

- Makefile.in
- Src/cmor_CV.c
- Test/test_cmor_nested_cv_attribute.py
Resolves #737
CMOR will now check the required attributes set by the user first before checking all required attributes listed in `required_global_attributes` in the CV. This allows for the setting of attributes nested within attributes such as the `domain_id` example in https://github.com/PCMDI/cmor/issues/737#issue-2240078052. In that example, `domain_id` will be validated first to allow the setting of the `domain` attribute. A second validation pass will then validate the `domain` attribute.
> Check user-defined required attributes before checking all required attributes

- Makefile.in
- Src/_controlvocabulary.c
- Src/cmor.c
- Test/test_cmor_path_and_file_templates.py
- TestTables/CMIP7_CV.json
- include/cmor.h
Resolves #834 
This will allow the use of the `directory_path_template` and `filename_template` attributes in the `DRS` section of CV files.  If the user defines `output_path_template` or `output_file_template` in the input JSON, then they will overwrite the path or file template defined by the CV's DRS.  If the `DRS` section is not present or `directory_path_template` or `filename_template` are not present in the section, then CMOR's default template values will be used. 
Some changes will need to be made to the DRS template values.  In [CMIP6_CV.json](https://github.com/PCMDI/cmip6-cmor-tables/blob/5d08a879bbc79657c367098a2b84279593e63551/Tables/CMIP6_CV.json#L3621), the file name template uses the pattern `[_<time_range>]`.  There is no `time_range` attribute in CMOR.  Rather, the time …
> Use directory path and file name template in DRS section of CV

- Src/_cmormodule.c
Resolves #828 
This error was fixed by casting the 2D array that holds the text parameter names as `char *` like the other arrays for parameter names and units.
> Fix compiler error in _cmormodue.c

- LibCV/PrePARE/PrePARE.py
Resolves #833 
The following warning will be printed when running PrePARE.
```
FutureWarning: PrePARE is a legacy application that is no longer supported as of CMOR 3.12 and will be removed in a future release.
```
> Add deprecation warning message to PrePARE

- Src/cmor_grids.c
- Test/test_cmor_crs.py
Resolves #845 
A warning message won't be displayed by `cmor_set_grid_mapping` or `cmor_set_crs`  for a missing `standard_parallel` parameter if passing two values with `standard_parallel1` and `standard_parallel2`.
This PR also allows the `albers_conical_equal_area` grid mapping to have two standard parallel values.
> Don't show warning if standard_parallel1 and standard_parallel2 are used for grid mapping/CRS

- .circleci/config.yml
- .github/workflows/nightly-build.yml
Due to [conda-forge dropping support for Python 3.9](https://conda-forge.org/news/2025/08/18/python-3-9/), we are removing Python 3.9 nightly builds.
> Remove Python 3.9 build from nightly

- Makefile.in
- Src/cmor_axes.c
- Src/cmor_variables.c
- Test/test_cmor_time_value_and_bounds_mismatch.py
- Test/test_python_CMIP6_CV_forcenoparent.py
- include/cmor_func_def.h
Resolves #852 
If the user passes time values that are not approximately (within 10<sup>-6</sup> days of) the midpoints computed from the time bounds passed, then the following warning message will be printed.
```
C Traceback:
In function: cmor_values_from_bounds
! called from: cmor_axis
! 
!
! Warning: The values you provided for axis time are different from those computed from the bounds, which are used for the axis values instead of the user-provided values.
!
! The first value found is at index 0: 0.000000 will be replaced with 15.000000 between bounds 0.000000 and 30.000000
!
```
> Warn users when the time values they pass don't match those created from the bounds they pass

- Src/cmor_CV.c
`nominal_resolution` in the CV should be either an array or dictionary with key-value pairs.  However, the grid checking function only looks for an array. This quick patch adds the check for the dictionary.
It's a bit redundant since the issue will also get caught by the global attribute check but I wanted the check to match the one done for `grid_label` in the same function.
Not a blocker for the CMOR 3.12 release.
> Check if nominal_resolution value is found in a dictionary in the CV in grid check
